**Question: Find the key with maximum value in a dictionary**

In [ ]:
print("SOLVED EXAMPLE:")
print("Find the key with maximum value in a dictionary")
scores = {'Alice': 85, 'Bob': 92, 'Charlie': 78, 'Diana': 95, 'Eve': 88}
max_key = max(scores, key=scores.get)
max_value = scores[max_key]
print(f"Dictionary: {scores}")
print(f"Key with maximum value: {max_key}")
print(f"Maximum value: {max_value}")
print("-" * 50)

SOLVED EXAMPLE:
Find the key with maximum value in a dictionary
Dictionary: {'Alice': 85, 'Bob': 92, 'Charlie': 78, 'Diana': 95, 'Eve': 88}
Key with maximum value: Diana
Maximum value: 95
--------------------------------------------------


**Question 1: Create a dictionary of student names and their ages**

In [ ]:
print("Question 1: Create a dictionary of student names and their ages")

students={
    "Alice":30,
    "Bob":25,
    "charlie":15,

}

print(students)


Question 1: Create a dictionary of student names and their ages
{'Alice': 30, 'Bob': 25, 'charlie': 15}


**Question 2: Add a new key-value pair to dictionary {'a': 1, 'b': 2, 'c': 3}**

In [ ]:
print("\nQuestion 2: Add a new key-value pair to dictionary {'a': 1, 'b': 2, 'c': 3}")

my_dict={'a': 1, 'b': 2, 'c': 3}
my_dict['d']=4
print(my_dict)


Question 2: Add a new key-value pair to dictionary {'a': 1, 'b': 2, 'c': 3}
{'a': 1, 'b': 2, 'c': 3, 'd': 4}


**Question 3: Get all keys from dictionary {'name': 'John', 'age': 25, 'city': 'New York'}
**

In [ ]:
print("\nQuestion 3: Get all keys from dictionary {'name': 'John', 'age': 25, 'city': 'New York'}")

my_dist={'name': 'John', 'age': 25, 'city': 'New York'}
print(my_dist.keys())



Question 3: Get all keys from dictionary {'name': 'John', 'age': 25, 'city': 'New York'}
dict_keys(['name', 'age', 'city'])


**Question 4: Get all values from dictionary {'python': 3, 'java': 2, 'c++': 1}**

In [ ]:
print("\nQuestion 4: Get all values from dictionary {'python': 3, 'java': 2, 'c++': 1}")

my_dist= {'python': 3, 'java': 2, 'c++': 1}
print(my_dist.values())



Question 4: Get all values from dictionary {'python': 3, 'java': 2, 'c++': 1}
dict_values([3, 2, 1])


**Question 5: Check if key 'age' exists in {'name': 'Alice', 'age': 30, 'city': 'London'}**

In [ ]:
print("\nQuestion 5: Check if key 'age' exists in {'name': 'Alice', 'age': 30, 'city': 'London'}")

my_dist={'name': 'Alice', 'age': 30, 'city': 'London'}
print('age' in my_dist)


Question 5: Check if key 'age' exists in {'name': 'Alice', 'age': 30, 'city': 'London'}
True


**Question 6: Remove key 'temp' from {'a': 1, 'b': 2, 'temp': 3, 'c': 4}**

In [ ]:
print("\nQuestion 6: Remove key 'temp' from {'a': 1, 'b': 2, 'temp': 3, 'c': 4}")

my_dist={'a': 1, 'b': 2, 'temp': 3, 'c': 4}
my_dist.pop('temp')
print(my_dist)



Question 6: Remove key 'temp' from {'a': 1, 'b': 2, 'temp': 3, 'c': 4}
{'a': 1, 'b': 2, 'c': 4}


**Question 7: Find the sum of all values in {'math': 85, 'science': 92, 'english': 78}**

In [ ]:
print("\nQuestion 7: Find the sum of all values in {'math': 85, 'science': 92, 'english': 78}")

scores = {'math': 85, 'science': 92, 'english': 78}
for subject, score in scores.items():
    print(f"{subject}: {score}")
total_score = sum(scores.values())
print("Total Score:", total_score)


Question 7: Find the sum of all values in {'math': 85, 'science': 92, 'english': 78}
math: 85
science: 92
english: 78
Total Score: 255


**Question 8: Create a dictionary with squares of numbers 1 to 5**

In [ ]:
print("\nQuestion 8: Create a dictionary with squares of numbers 1 to 5")

squares = {num: num**2 for num in range(1, 6)}
print(squares)



Question 8: Create a dictionary with squares of numbers 1 to 5
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


**Question 9: Count frequency of each character in string "hello"**

In [ ]:
print("\nQuestion 9: Count frequency of each character in string 'hello'")

string="hello"
frequency={}
for char in string:
  frequency[char]=frequency.get(char,0)+1
print(frequency)




Question 9: Count frequency of each character in string 'hello'
{'h': 1, 'e': 1, 'l': 2, 'o': 1}


**Question 10: Merge two dictionaries {'a': 1, 'b': 2} and {'c': 3, 'd': 4}**

In [ ]:
print("\nQuestion 10: Merge two dictionaries {'a': 1, 'b': 2} and {'c': 3, 'd': 4}")

dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}
dict1.update(dict2)
print(dict1)


Question 10: Merge two dictionaries {'a': 1, 'b': 2} and {'c': 3, 'd': 4}
{'a': 1, 'b': 2, 'c': 3, 'd': 4}


**Question 11: Create a nested dictionary: {'person': {'name': 'Alice', 'age': 25}}**

In [ ]:
print("\nQuestion 11: Create a nested dictionary: {'person': {'name': 'Alice', 'age': 25}}")

nested_dict = {'person': {'name': 'Alice', 'age': 25}}
print(nested_dict)


Question 11: Create a nested dictionary: {'person': {'name': 'Alice', 'age': 25}}
{'person': {'name': 'Alice', 'age': 25}}


**Question 12: Access nested value 'name' from {'person': {'name': 'Alice', 'age': 25}}**

In [ ]:
print("\nQuestion 12: Access nested value 'name' from {'person': {'name': 'Alice', 'age': 25}}")

nested_dict = {'person': {'name': 'Alice', 'age': 25}}
print(nested_dict['person']['name'])


Question 12: Access nested value 'name' from {'person': {'name': 'Alice', 'age': 25}}
Alice


**Question 13: Create a dictionary with list values: {'fruits': ['apple', 'banana'], 'colors': ['red', 'blue']}**

In [ ]:
print("\nQuestion 13: Create a dictionary with list values: {'fruits': ['apple', 'banana'], 'colors': ['red', 'blue']}")

dict_with_lists = {'fruits': ['apple', 'banana'], 'colors': ['red', 'blue']}
print(dict_with_lists)



Question 13: Create a dictionary with list values: {'fruits': ['apple', 'banana'], 'colors': ['red', 'blue']}
{'fruits': ['apple', 'banana'], 'colors': ['red', 'blue']}


**Question 14: Add 'orange' to the 'fruits' list in nested dictionary**

In [ ]:
print("\nQuestion 14: Add 'orange' to the 'fruits' list in nested dictionary")
dict_with_lists = {'fruits': ['apple', 'banana'], 'colors': ['red', 'blue']}
print(f'Before Asdding: {dict_with_lists}')
dict_with_lists['fruits'].append('orange')
print(f'After Adding: {dict_with_lists}')


Question 14: Add 'orange' to the 'fruits' list in nested dictionary
Before Asdding: {'fruits': ['apple', 'banana'], 'colors': ['red', 'blue']}
After Adding: {'fruits': ['apple', 'banana', 'orange'], 'colors': ['red', 'blue']}


**Question 15: Create a dictionary with tuple values: {'coordinates': (10, 20), 'rgb': (255, 0, 0)}**

In [ ]:
print("\nQuestion 15: Create a dictionary with tuple values: {'coordinates': (10, 20), 'rgb': (255, 0, 0)}")

dict_with_tuples = {'coordinates': (10, 20), 'rgb': (255, 0, 0)}
print(dict_with_tuples)



Question 15: Create a dictionary with tuple values: {'coordinates': (10, 20), 'rgb': (255, 0, 0)}
{'coordinates': (10, 20), 'rgb': (255, 0, 0)}


**Question 16: Extract first coordinate from nested tuple**

In [ ]:
print("\nQuestion 16: Extract first coordinate from nested tuple")

tuple1=((1,2),(3,4),(5,6))
first_coordinate=[i[0] for i in tuple1]
print(first_coordinate)



Question 16: Extract first coordinate from nested tuple
[1, 3, 5]


**Question 17: Create a dictionary with set values: {'vowels': {'a', 'e', 'i'}, 'consonants': {'b', 'c', 'd'}}**

In [ ]:
print("\nQuestion 17: Create a dictionary with set values: {'vowels': {'a', 'e', 'i'}, 'consonants': {'b', 'c', 'd'}}")

dict_setvalue={
    'vowels': {'a', 'e', 'i'},
    'consonants': {'b', 'c', 'd'}

    }

print(dict_setvalue)


Question 17: Create a dictionary with set values: {'vowels': {'a', 'e', 'i'}, 'consonants': {'b', 'c', 'd'}}
{'vowels': {'i', 'e', 'a'}, 'consonants': {'d', 'b', 'c'}}


**Question 18: Add 'o' to vowels set in nested dictionary**

In [ ]:
print("\nQuestion 18: Add 'o' to vowels set in nested dictionary")

dict_setvalue={
    'vowels': {'a', 'e', 'i'},
    'consonants': {'b', 'c', 'd'}

    }
dict_setvalue['vowels']={'a','e','i','o'}
print(dict_setvalue)




Question 18: Add 'o' to vowels set in nested dictionary
{'vowels': {'i', 'e', 'a', 'o'}, 'consonants': {'d', 'b', 'c'}}


**Question 19: Create a 3-level nested dictionary**

In [ ]:
print("\nQuestion 19: Create a 3-level nested dictionary: {'company': {'department': {'employee': {'name': 'John', 'id': 123}}}}")

level3_dict= {'company': {'department': {'employee': {'name': 'John', 'id': 123}}}}
print(level3_dict)


Question 19: Create a 3-level nested dictionary: {'company': {'department': {'employee': {'name': 'John', 'id': 123}}}}
{'company': {'department': {'employee': {'name': 'John', 'id': 123}}}}


**Question 20: Access employee name from 3-level nested dictionary**

In [ ]:
print("\nQuestion 20: Access employee name from 3-level nested dictionary")

level3_dict={'company': {'department': {'employee': {'name': 'John', 'id': 123}}}}
print(level3_dict['company']['department']['employee']['name'])


Question 20: Access employee name from 3-level nested dictionary
John


**Question 21: Create a dictionary with mixed data types**

In [ ]:
print("\nQuestion 21: Create a dictionary with mixed data types: {'int': 42, 'float': 3.14, 'str': 'hello', 'bool': True}")

dict_mixed={'int': 42, 'float': 3.14, 'str': 'hello', 'bool': True}
print(dict_mixed)


Question 21: Create a dictionary with mixed data types: {'int': 42, 'float': 3.14, 'str': 'hello', 'bool': True}
{'int': 42, 'float': 3.14, 'str': 'hello', 'bool': True}


**Question 22: Check data type of each value in mixed dictionary**

In [ ]:
print("\nQuestion 22: Check data type of each value in mixed dictionary")

mixed_dict={'int': 42, 'float': 3.14, 'str': 'hello', 'bool': True}
print(type(mixed_dict['int']))
print(type(mixed_dict['float']))
print(type(mixed_dict['str']))
print(type(mixed_dict['bool']))





Question 22: Check data type of each value in mixed dictionary
<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


**Question 23: Create a dictionary with function values**

In [ ]:
print("\nQuestion 23: Create a dictionary with function values: {'len': len, 'str': str, 'int': int}")

func_dict={'len': len, 'str': str, 'int': int}
print(func_dict)


Question 23: Create a dictionary with function values: {'len': len, 'str': str, 'int': int}
{'len': <built-in function len>, 'str': <class 'str'>, 'int': <class 'int'>}


**Question 24: Apply each function to "123" using dictionary**

In [ ]:
print("\nQuestion 24: Apply each function to '123' using dictionary")

func_dict={'len': len, 'str': str, 'int': int}
print(func_dict['len']('123'))
print(func_dict['str']('123'))
print(func_dict['int']('123'))




Question 24: Apply each function to '123' using dictionary
3
123
123



**Question 25: Create a dictionary with lambda functions**

In [ ]:
print("\nQuestion 25: Create a dictionary with lambda functions: {'double': lambda x: x*2, 'square': lambda x: x**2}")

dict_lambda={'double': lambda x: x*2, 'square': lambda x: x**2}
print(dict_lambda)


Question 25: Create a dictionary with lambda functions: {'double': lambda x: x*2, 'square': lambda x: x**2}
{'double': <function <lambda> at 0x7a6b7b1a67a0>, 'square': <function <lambda> at 0x7a6b7b1a6840>}


**Question 26: Apply each lambda function to 5**

In [ ]:
print("\nQuestion 26: Apply each lambda function to 5")
dict_lambda={
    'double': lambda x: x*2,
    'square': lambda x: x**2
    }
print(dict_lambda['double'](5))
print(dict_lambda['square'](5))



Question 26: Apply each lambda function to 5
10
25


 **Question 27: Create a dictionary with class values**

In [ ]:
print("\nQuestion 27: Create a dictionary with class values: {'list': list, 'dict': dict, 'set': set}")

dict_values={
    'list': list,
    'dict': dict,
    'set': set
    }
print(dict_values)


Question 27: Create a dictionary with class values: {'list': list, 'dict': dict, 'set': set}
{'list': <class 'list'>, 'dict': <class 'dict'>, 'set': <class 'set'>}


**Question 28: Create instances using class dictionary**

In [ ]:
print("\nQuestion 28: Create instances using class dictionary")

class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

p = Person("Alice", 25)
print((p.__dict__))


Question 28: Create instances using class dictionary
{'name': 'Alice', 'age': 25}


**Question 29: Create a dictionary with None values**

In [ ]:
print("\nQuestion 29: Create a dictionary with None values: {'a': None, 'b': None, 'c': None}")

dict_none={
    'a': None,
    'b': None,
    'c': None
    }
print(dict_none)



Question 29: Create a dictionary with None values: {'a': None, 'b': None, 'c': None}
{'a': None, 'b': None, 'c': None}


**Question 30: Replace all None values with 0**

In [ ]:
print("\nQuestion 30: Replace all None values with 0")

dict_none={
    'a': None,
    'b': None,
    'c': None
    }
dict_none['a']=0
dict_none['b']=0
dict_none['c']=0
print(dict_none)




Question 30: Replace all None values with 0
{'a': 0, 'b': 0, 'c': 0}


**Question 31: Create a dictionary with boolean values**

In [ ]:
print("\nQuestion 31: Create a dictionary with boolean values: {'is_active': True, 'is_admin': False}")

dict_boolvalue={'is_active': True, 'is_admin': False}
print(dict_boolvalue)


Question 31: Create a dictionary with boolean values: {'is_active': True, 'is_admin': False}
{'is_active': True, 'is_admin': False}


**Question 32: Count True values in boolean dictionary**

In [ ]:
print("\nQuestion 32: Count True values in boolean dictionary")

dict_boolvalue={
    'is_active': True,
    'is_admin': False
    }
count=0
for key,value in dict_boolvalue.items():
  if dict_boolvalue[key]==True:
    count=count+1

print(count)




Question 32: Count True values in boolean dictionary
1


**Question 33: Create a dictionary with complex numbers**

In [ ]:
print("\nQuestion 33: Create a dictionary with complex numbers: {'z1': 3+4j, 'z2': 1+2j}")

dict_cmplxnum={
    'z1': 3+4j,
    'z2': 1+2j
    }
print(dict_cmplxnum)


Question 33: Create a dictionary with complex numbers: {'z1': 3+4j, 'z2': 1+2j}
{'z1': (3+4j), 'z2': (1+2j)}


**Question 34: Find magnitude of each complex number**

In [ ]:
print("\nQuestion 34: Find magnitude of each complex number")

dict_cmplxnum={
    'z1': 3+4j,
    'z2': 1+2j
    }
magnitudes={}
for key,value in dict_cmplxnum.items():
  magnitudes[key]=abs(value)

print(magnitudes)



Question 34: Find magnitude of each complex number
{'z1': 5.0, 'z2': 2.23606797749979}


**Question 35: Create a 4-level nested dictionary**

In [ ]:
print("\nQuestion 35: Create a 4-level nested dictionary")

dict_level4= {
    'employer' : {
        'department' : {
            'employee' : {
                'projects_handling' : {
                    'client' : 'Ford',
                    'language_used' : 'Data Science'
                }
            }
        }
    }
}
print(dict_level4)


Question 35: Create a 4-level nested dictionary
{'employer': {'department': {'employee': {'projects_handling': {'client': 'Ford', 'language_used': 'Data Science'}}}}}


**Question 36: Access deepest value in 4-level nested dictionary**

In [ ]:
print("\nQuestion 36: Access deepest value in 4-level nested dictionary")

dict_level4= {
    'employer' : {
        'department' : {
            'employee' : {
                'projects_handling' : {
                    'client' : 'Ford',
                    'language_used' : 'Data Science'
                }
            }
        }
    }
}
print(dict_level4['employer']['department']['employee']['projects_handling'])


Question 36: Access deepest value in 4-level nested dictionary
{'client': 'Ford', 'language_used': 'Data Science'}


**Question 37: Create a dictionary with range values**

In [ ]:
print("\nQuestion 37: Create a dictionary with range values: {'r1': range(3), 'r2': range(5)}")

dict_range={'r1': range(3), 'r2': range(5)}
print(dict_range)


Question 37: Create a dictionary with range values: {'r1': range(3), 'r2': range(5)}
{'r1': range(0, 3), 'r2': range(0, 5)}


**Question 38: Convert each range to list**

In [ ]:
print("\nQuestion 38: Convert each range to list")

dict_range={'r1': range(3), 'r2': range(5)}

for key, value in dict_range.items() :
  dict_range[key] = list(value)
print(dict_range)



Question 38: Convert each range to list
{'r1': [0, 1, 2], 'r2': [0, 1, 2, 3, 4]}


**Question 39: Create a dictionary with generator values**

In [ ]:
print("\nQuestion 39: Create a dictionary with generator values")

dict_gen={

        'gen1':(i for i in range(3)),
        'gen2':(i**2 for i in range(3))
}

print(dict_gen)



Question 39: Create a dictionary with generator values
{'gen1': <generator object <genexpr> at 0x7bdb3a313880>, 'gen2': <generator object <genexpr> at 0x7bdb3a1ebc60>}


**Question 40: Convert each generator to list**

In [ ]:
print("\nQuestion 40: Convert each generator to list")

dict_gen={

        'gen1':(i for i in range(3)),
        'gen2':(i**2 for i in range(3))
}

for key,value in dict_gen.items():
  dict_gen[key]=list(value)

print(dict_gen)




Question 40: Convert each generator to list
{'gen1': [0, 1, 2], 'gen2': [0, 1, 4]}


**Question 41: Create a dictionary with iterator values**

In [ ]:
print("\nQuestion 41: Create a dictionary with iterator values")

iter_dict = {
    'it1': iter([1, 2, 3]),
    'it2': iter('abc')
}

print(iter_dict)



Question 41: Create a dictionary with iterator values
{'it1': <list_iterator object at 0x7bdb3aad4490>, 'it2': <str_ascii_iterator object at 0x7bdb3aa981f0>}


**Question 42: Extract all elements from each iterator**

In [ ]:
iter_dict = {
    'it1': iter([1, 2, 3]),
    'it2': iter('abc')
}

extracted = {}

for key, it in iter_dict.items():
    extracted[key] = list(it)

print(extracted)

{'it1': [1, 2, 3], 'it2': ['a', 'b', 'c']}


**Question 43: Create a dictionary with nested lists:**

In [ ]:
print("\nQuestion 43: Create a dictionary with nested lists: {'matrix': [[1, 2], [3, 4]], 'vector': [5, 6, 7]}")

nested_dict={
    'matrix': [[1, 2], [3, 4]],
    'vector': [5, 6, 7]
    }
print(nested_dict)


Question 43: Create a dictionary with nested lists: {'matrix': [[1, 2], [3, 4]], 'vector': [5, 6, 7]}
{'matrix': [[1, 2], [3, 4]], 'vector': [5, 6, 7]}


**Question 44: Find sum of each nested list**

In [4]:
print("\nQuestion 44: Find sum of each nested list")

nested_list={
    'matrix': [[1, 2], [3, 4]],
    'vector': [5, 6, 7]
    }
sum_dict={}
for key, value in nested_list.items():
    total = 0
    for item in value:
        if isinstance(item, list):
            total += sum(item)
        else:
            total += item
    sum_dict[key] = total

print(sum_dict)


Question 44: Find sum of each nested list
{'matrix': 10, 'vector': 18}


**Question45:Create a dictionary with nested dictionaries:**

In [6]:
print("\nQuestion 45: Create a dictionary with nested dictionaries: {'config': {'db': {'host': 'localhost', 'port': 5432}}}")

nested_dict={
    'config': {
        'db': {
            'host': 'localhost',
            'port': 5432
            }
        }
    }
print(nested_dict)



Question 45: Create a dictionary with nested dictionaries: {'config': {'db': {'host': 'localhost', 'port': 5432}}}
{'config': {'db': {'host': 'localhost', 'port': 5432}}}


 **Question 46: Access database port from nested configuration**

In [7]:
print("\nQuestion 46: Access database port from nested configuration")

nested_dict={
    'config': {
        'db': {
            'host': 'localhost',
            'port': 5432
            }
        }
    }

print(nested_dict['config']['db']['port'])



Question 46: Access database port from nested configuration
5432


**Question 47: Create a dictionary with nested tuples:**

In [8]:
print("\nQuestion 47: Create a dictionary with nested tuples: {'points': ((1, 2), (3, 4)), 'rgb': ((255, 0, 0), (0, 255, 0))}")

nested_tuple={
    'points': ((1, 2), (3, 4)),
    'rgb': ((255, 0, 0), (0, 255, 0))
    }
print(nested_tuple)


Question 47: Create a dictionary with nested tuples: {'points': ((1, 2), (3, 4)), 'rgb': ((255, 0, 0), (0, 255, 0))}
{'points': ((1, 2), (3, 4)), 'rgb': ((255, 0, 0), (0, 255, 0))}


**Question 48: Extract first point coordinates**

In [9]:
print("\nQuestion 48: Extract first point coordinates")

nested_tuple={
    'points': ((1, 2), (3, 4)),
    'rgb': ((255, 0, 0), (0, 255, 0))
    }
print(nested_tuple['points'][0])



Question 48: Extract first point coordinates
(1, 2)


**Question 49: Create a dictionary with nested sets:**

In [12]:
print("\nQuestion 49: Create a dictionary with nested sets: {'groups': {{1, 2, 3}, {4, 5, 6}}, 'categories': {{'a', 'b'}, {'c', 'd'}}}")

nested_sets = {
    'groups': {frozenset({1, 2, 3}), frozenset({4, 5, 6})},
    'categories': {frozenset({'a', 'b'}), frozenset({'c', 'd'})}
}
print(nested_sets)


Question 49: Create a dictionary with nested sets: {'groups': {{1, 2, 3}, {4, 5, 6}}, 'categories': {{'a', 'b'}, {'c', 'd'}}}
{'groups': {frozenset({1, 2, 3}), frozenset({4, 5, 6})}, 'categories': {frozenset({'d', 'c'}), frozenset({'a', 'b'})}}


**Question 50: Find union of all nested sets**

In [14]:
print("\nQuestion 50: Find union of all nested sets")

nested_sets = {
    'groups': {frozenset({1, 2, 3}), frozenset({4, 5, 6})},
    'categories': {frozenset({'a', 'b'}), frozenset({'c', 'd'})}
}

union_dict = {}

for key, value in nested_sets.items():
  union_set = set()
  for fs in value:
    union_set = union_set | fs
  union_dict[key] = union_set

print(union_dict)


Question 50: Find union of all nested sets
{'groups': {1, 2, 3, 4, 5, 6}, 'categories': {'a', 'd', 'b', 'c'}}
